/******************************************************************************
 *                                                                            *
 * Compilar con g++ -o chat chat.cpp -std=c++11 -lfltk                        *
 *                                                                            *
 ******************************************************************************/
 
// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef chat_h
#define chat_h
#include <FL/Fl.H>
#include <FL/Fl_Text_Buffer.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>
#include <semaphore.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include <arpa/inet.h>
#include <errno.h>
#include <pthread.h>
#include <unistd.h>
#include <signal.h>


struct sockaddr_in ip;
sem_t asig, listo, output;
char buffer_l[1024];
char buffer_e[1024];

class UserInterface {
  Fl_Text_Buffer * m_Buffer; 
public:
  UserInterface();
  Fl_Double_Window *m_MainWindow;
  Fl_Text_Display *m_Output;
  Fl_Input *m_Input;
  Fl_Button *m_Send;
private:
  inline void cb_m_Send_i(Fl_Button*, void*);
  static void cb_m_Send(Fl_Button*, void*);
public:
  void show(int argc, char ** argv);
};
#endif
